import 'package:ePolli/app/core/theme/app_color.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'terms_conditions_controller.dart';

class TermsConditionsPage extends GetView<TermsConditionsController> {
  const TermsConditionsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('TermsConditionsPage'),
        centerTitle: true,
        backgroundColor: AppColor.secondary,
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(10.0),
          child: RichText(
            text: const TextSpan(
              style: TextStyle(color: AppColor.bText),
              children: <TextSpan>[
                TextSpan(
                  text: 'General Terms\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'By accessing and placing an order with ePolli, you acknowledge and agree to abide by the Terms & Conditions provided below. These terms govern the entire usage of the website and any form of communication between you and ePolli.\n',
                ),
                TextSpan(
                    text:
                        'ePolli and its team shall not be held liable under any circumstances for any direct, indirect, special, incidental, or consequential damages, including but not limited to data loss or profit loss, arising from the use or inability to use the materials on this site, even if ePolli or its authorized representatives have been informed of the possibility of such damages. If your use of materials from this site necessitates servicing, repair, or correction of equipment or data, you bear any associated costs.\n'),
                TextSpan(
                    text:
                        'Please note that ePolli will not assume responsibility for any outcomes that may arise during the utilization of our resources. Additionally, we reserve the right to modify prices and revise the resource usage policy at any time.\n\n'),
                TextSpan(
                  text: 'License\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'ePolli extends to you a limited, revocable, non-exclusive, and non-transferable license, allowing you to download, install, and utilize the app in strict accordance with the stipulations outlined in this Agreement. The present Terms & Conditions serve as a legally binding contract between you, the user, and ePolli ("we," "our," or "us"), conferring upon you the privilege to access and use the app under the specific conditions specified herein.\n\n',
                ),
                TextSpan(
                  text:
                      'It is important to emphasize that the license we grant you is subject to certain limitations, and we retain the right to revoke or modify it at any given time at our discretion. You must adhere to the terms and provisions of this Agreement to continue using the app in compliance with the established guidelines.\n\n',
                ),
                TextSpan(
                  text:
                      'This license allows you to access and utilize the ePolli app solely for personal, non-commercial purposes, ensuring that you do not transfer, sublicense, distribute, or exploit the app beyond the scope outlined in this Agreement. Any breach of these terms may result in the termination of the license and could lead to legal consequences.\n\n',
                ),

                // Adding a section break for definitions and key terms
                TextSpan(
                  text: 'Definitions & Key Terms\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text: 'For this Terms & Conditions:\n',
                ),
                TextSpan(
                  text:
                      '• Cookie: A small data snippet generated by a website and stored by your web browser, utilized to recognize your browser, offer analytics, and retain details such as language preferences or login information about you.\n',
                ),
                TextSpan(
                  text:
                      '• Company: In the context of this policy, when "Company," "we," "us," or "our" is mentioned, it pertains to ePolli Limited, located at 2nd Floor, 6/5 Ali-Noor Real State, Mohammadpur, Dhaka, 1207, Bangladesh, responsible for handling your information in accordance with this Privacy Policy.\n',
                ),
                TextSpan(
                  text:
                      '• Country: The country where ePolli or the owners/founders of ePolli are based is Bangladesh.\n',
                ),
                TextSpan(
                  text:
                      '• Customer: Refers to the company, organization, or individual who registers to use the ePolli Service to manage relationships with their consumers or service users.\n',
                ),
                TextSpan(
                  text:
                      '• Device: Any internet-connected device, such as a phone, tablet, computer, or any other tool that allows you to access ePolli and use its services.\n',
                ),
                TextSpan(
                  text:
                      '• IP address: An Internet protocol (IP) address assigned to every device connected to the Internet. These numbers are usually grouped geographically and can be used to determine the location from which a device connects to the Internet.\n',
                ),
                TextSpan(
                  text:
                      '• Personnel: Refers to individuals employed by ePolli or under contract to provide services on behalf of either party.\n',
                ),
                TextSpan(
                  text:
                      '• Personal Data: Any information that directly, indirectly, or in connection with other data, including personal identification numbers, enables the identification or identifiability of a natural person.\n',
                ),
                TextSpan(
                  text:
                      '• Service: Pertains to the services offered by ePolli as described in the relevant terms (if available) and on this platform.\n',
                ),
                TextSpan(
                  text:
                      '• Third-party service: Relates to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we believe may interest you.\n',
                ),
                TextSpan(
                  text:
                      '• Website: ePolli’s site, which can be accessed via this URL: www.epolli.com.bd\n',
                ),
                TextSpan(
                  text:
                      '• You: a person or entity that is registered with ePolli to use the Services\n\n',
                ),
                // Adding a section break for Restrictions
                TextSpan(
                  text: 'Restrictions\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'By giving your consent, you hereby commit and pledge not to engage in, and you shall prevent others from engaging in the following activities:\n',
                ),
                TextSpan(
                  text:
                      '• Licensing, selling, renting, leasing, assigning, distributing, transmitting, hosting, outsourcing, disclosing, or engaging in any form of commercial exploitation of the service or making the platform available to any third party.\n',
                ),
                TextSpan(
                  text:
                      '• Altering, modifying, creating derivative works from, disassembling, decrypting, reverse compiling, or reverse engineering any portion of the service.\n',
                ),
                TextSpan(
                  text:
                      '• Removing, tampering with, altering, or obfuscating any proprietary notice, including but not limited to copyright or trademark notices, belonging to the service\'s affiliates, partners, suppliers, or licensors.\n',
                ),
                TextSpan(
                  text:
                      'By agreeing to these terms, you understand and acknowledge that any violation of these provisions may result in legal consequences and may also infringe upon the intellectual property rights of the service and its associated entities. Hence, you are obliged to strictly adhere to these restrictions and prevent any unauthorized use or access to the service. These measures aim to safeguard the integrity and security of the platform, as well as protect the intellectual property and proprietary rights of all stakeholders involved.\n\n',
                ),

                // Adding a section break for Return and Refund Policy
                TextSpan(
                  text: 'Return and Refund Policy\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'We extend our sincerest gratitude for choosing us as your preferred shopping destination. It brings us immense joy to know that you have found our products appealing and worthy of purchase. Our utmost priority is to ensure that your journey of exploration, evaluation, and acquisition of our offerings is both gratifying and fulfilling.\n\n',
                ),
                TextSpan(
                  text:
                      'As with any business transaction, certain terms and conditions govern the interactions at our esteemed company. We understand the importance of being concise, yet comprehensive, in conveying this information, as dictated by our legal advisors. It is imperative to emphasize that upon placing an order for any agro processing foods or opting for project financing from our institution, you willingly and wholeheartedly agree to adhere to these terms, in conjunction with our esteemed Privacy Policy.\n\n',
                ),
                TextSpan(
                  text:
                      'Should you experience any change of decision pertaining to the financing aspect, we assure you that any issues will be addressed with utmost diligence and in accordance with our Financial Settlement Processes. We prioritize your satisfaction and strive to provide swift resolutions to any concerns that may arise during this process.\n\n',
                ),

                // Adding a section break for Modality
                TextSpan(
                  text: 'Modality\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'The ePolli project financing terms outline the consequences of premature project closure initiated by the financier.\n\n',
                ),
                TextSpan(
                  text:
                      'If such an event occurs, the investor will not be entitled to any profits from the project. To facilitate a smooth transition, we kindly request a notice period of 15 working days, during which we will ensure the arrangement of a suitable replacement for the finance.\n\n',
                ),
                TextSpan(
                  text:
                      'In situations where the project closure transpires prior to completing 20% of its designated duration, the entire financed amount will be promptly returned to the investor without any deductions or service charges applied. However, if the closure takes place after crossing the 20% project completion threshold, a service charge equivalent to 2% of the financed amount or BDT 2,500 (whichever amount is lower) will be applicable as per ePolli\'s policy.\n',
                ),
                // Adding a section break for Your Suggestions
                TextSpan(
                  text: 'Your Suggestions\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'Any feedback, comments, ideas, improvements, or suggestions (collectively referred to as "Suggestions") shared by you with regards to the service shall be deemed the exclusive property of ePolli. We retain the unrestricted right to utilize, reproduce, modify, publish, or redistribute the Suggestions for any purpose and in any manner, without the need for crediting or providing any compensation to you. You may share your Suggestions through various channels, including the email address: support@epolli.com.bd, our customer care numbers (01798101013, 09678221013), and our official social media platforms.\n\n',
                ),

                // Adding a section break for Your Consent
                TextSpan(
                  text: 'Your Consent\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'We have recently revised our Terms & Conditions to offer you utmost transparency regarding the information collected when you visit our website and how it is utilized. Your usage of our service, registration of an account, or completion of a purchase implies your explicit consent to abide by our updated Terms & Conditions.\n\n',
                ),

                // Adding a section break for Links to Other Websites
                TextSpan(
                  text: 'Links to Other Websites\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'Within our service, you may come across links to external websites that are not under our direct control and management. Should you choose to click on any of these third-party links, you will be redirected to the respective third party\'s website. As a precautionary measure, we highly recommend that you diligently review and familiarize yourself with the Terms & Conditions of each site you visit.\n\n',
                ),
                TextSpan(
                  text:
                      'It is essential to note that we do not exercise authority over the content, Terms & Conditions, or operational practices of these third-party websites or services. Consequently, we cannot assume any responsibility for the accuracy, appropriateness, legality, or any other aspect of the materials or actions presented on such external sites.\n\n',
                ),

                // Adding a section break for Cookies
                TextSpan(
                  text: 'Cookies\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'In order to identify the specific areas of our website that you have visited, we employ "Cookies," which are small data files stored on your computer or mobile device by your web browser. These Cookies serve to optimize the performance and functionality of our service, although they are not essential for its basic operation. Nevertheless, their absence may result in certain functionalities, such as videos, becoming inaccessible, or requiring you to input your login credentials during each visit, as our platform will be unable to recall your previous login.\n\n',
                ),
                TextSpan(
                  text:
                      'It is important to note that most web browsers offer the option to disable the use of Cookies. However, by doing so, you might encounter difficulties accessing certain features on our website, or you may be unable to access our platform altogether. Rest assured, we do not include any Personally Identifiable Information within these Cookies, ensuring the protection of your privacy.\n\n',
                ),

                // Adding a section break for Changes to Terms & Conditions
                TextSpan(
                  text: 'Changes to Terms & Conditions\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'As an ePolli user, you explicitly acknowledge and consent to the fact that we reserve the right to discontinue offering the Service, either permanently or temporarily, to you or all users, at our sole discretion, without any prior notice. Similarly, you maintain the freedom to cease using the Service at any point in time, and there is no obligation for you to provide specific notification when doing so.\n\n',
                ),
                TextSpan(
                  text:
                      'Furthermore, you understand and agree that in the event we disable access to your ePolli account, it may result in the prevention of your ability to access the Service, including your account details, files, or any other materials associated with your account.\n\n',
                ),
                TextSpan(
                  text:
                      'As part of our commitment to keeping you informed, should there be any modifications to our Terms & Conditions, we will promptly publish those changes on this page and update the "Terms & Conditions modification date" below. Your continued use of the ePolli Service after such modifications signifies your acceptance of the updated terms. We recommend periodically reviewing this page to stay informed about any alterations that may affect your use of the ePolli platform.\n\n',
                ),

                // Adding a section break for Modifications to Our service
                TextSpan(
                  text: 'Modifications to Our Service\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'We retain the prerogative to make alterations, suspend, or terminate, either temporarily or permanently, the service or any linked services, with or without prior notice, and without incurring any liability towards you.\n\n',
                ),
                // Adding a section break for Updates to Our service
                TextSpan(
                  text: 'Updates to Our Service\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'As part of our commitment to continually enhance the ePolli’s services, we may periodically introduce improvements or advancements to its features and functionality. These enhancements, referred to as "Updates," could encompass patches, bug fixes, updates, upgrades, and other modifications that may alter or remove specific features and functionalities of the service.\n\n',
                ),
                TextSpan(
                  text:
                      'By staying with ePolli, you acknowledge and agree to the following:\n',
                ),
                TextSpan(
                  text:
                      '• We hold no obligation to maintain or provide certain features and functionalities of the service to you indefinitely.\n',
                ),
                TextSpan(
                  text:
                      '• All Updates shall be considered an essential and integrated component of the ePolli’s services.\n',
                ),
                TextSpan(
                  text:
                      '• The Updates shall be governed by the terms and conditions outlined in this Agreement.\n\n',
                ),
                TextSpan(
                  text:
                      'Rest assured, these Updates are designed to elevate your overall user experience and ensure the continuous improvement of the ePolli’s platform.\n\n',
                ),

// Adding a section break for Third-Party Services
                TextSpan(
                  text: 'Third-Party Services\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services (“Third-Party Services”). You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services. Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties’ terms and conditions.\n\n',
                ),

// Adding a section break for Term and Termination
                TextSpan(
                  text: 'Term and Termination\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'This Agreement shall remain in effect until terminated by you or ePolli. We may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the service and all copies thereof from your computer. Upon termination of this Agreement, you shall cease all use of the service and delete all copies of the service from your computer. Termination of this Agreement will not limit any of our rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.\n\n',
                ),
                // Adding a section break for Copyright Infringement Notice
                TextSpan(
                  text: 'Copyright Infringement Notice\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'If you, as a copyright owner or an authorized agent of the copyright owner, believe that any material provided by us constitutes an infringement upon your copyright, we request you to reach out to us with the following details:\n',
                ),
                TextSpan(
                  text:
                      '(a) A physical or electronic signature of the copyright owner or an individual authorized to act on their behalf.\n',
                ),
                TextSpan(
                  text:
                      '(b) Clear identification of the material that is being claimed as infringing.\n',
                ),
                TextSpan(
                  text:
                      '(c) Your contact information, including your address, telephone number, and email.\n',
                ),
                TextSpan(
                  text:
                      '(d) A statement affirming that you have a good faith belief that the use of the material is not authorized by the copyright owner.\n',
                ),
                TextSpan(
                  text:
                      '(e) A statement confirming the accuracy of the information provided in the notification, and a declaration, under penalty of perjury, that you are duly authorized to represent the copyright owner.\n\n',
                ),
                TextSpan(
                  text:
                      'Upon receipt of such a notification, we will take the necessary steps to address the copyright infringement claim promptly and in accordance with applicable laws and regulations. Our commitment to upholding copyright protections is of utmost importance, and we appreciate your cooperation in bringing any potential infringements to our attention.\n\n',
                ),

// Adding a section break for Indemnification
                TextSpan(
                  text: 'Indemnification\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'You agree to indemnify and hold us and our parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys’ fees, due to or arising out of your:\n',
                ),
                TextSpan(
                  text: '(a) use of the service;\n',
                ),
                TextSpan(
                  text:
                      '(b) violation of this Agreement or any law or regulation; or\n',
                ),
                TextSpan(
                  text: '(c) violation of any right of a third party.\n\n',
                ),
                // Adding a section break for No Warranties
                TextSpan(
                  text: 'No Warranties\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'The service is provided "AS IS" and "AS AVAILABLE," and without any warranties, express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement. We, along with our affiliates, licensors, and service providers, expressly disclaim all warranties to the maximum extent permitted by applicable law. This includes warranties arising from course of dealing, course of performance, usage, or trade practice.\n\n',
                ),
                TextSpan(
                  text:
                      'We do not provide any warranty or guarantee that the service will meet your requirements, achieve desired results, be compatible with other software, websites, systems, or services, operate without interruption, meet specific performance or reliability standards, or be free from errors or defects. Additionally, we make no representation or warranty concerning the operation or availability of the service, the accuracy, reliability, or currency of information or content provided through the service, or the absence of viruses or harmful components in the service, its servers, content, or emails.\n\n',
                ),
                TextSpan(
                  text:
                      'Please note that some jurisdictions may not allow the exclusion of implied warranties or certain limitations on consumer statutory rights, and therefore, some or all of the above exclusions and limitations may not apply to you.\n\n',
                ),

// Adding a section break for Limitation of Liability
                TextSpan(
                  text: 'Limitation of Liability\n',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                TextSpan(
                  text:
                      'Despite any damages that may occur, the entire liability of ePolli and its suppliers under any provision of this Agreement, and your sole remedy for all such matters, shall be restricted to the actual amount paid by you for using the ePolli service. To the fullest extent permissible by applicable law, neither ePolli nor its suppliers shall be liable for any special, incidental, indirect, or consequential damages whatsoever. These damages may include, but are not limited to, loss of profits, loss of data or other information, business interruption, personal injury, or loss of privacy arising from the use of or inability to use the ePolli service, third-party software, and/or third-party hardware used in conjunction with the service, or any other provision of this Agreement. This limitation applies even if ePolli or any of its suppliers have been advised of the possibility of such damages and even if the remedy fails its essential purpose. Please note that in some states or jurisdictions, the exclusion or limitation of incidental or consequential damages may not be permitted, and thus, the above limitation or exclusion may not apply to you.\n\n',
                ),
                TextSpan(
                  text: 'Severability\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect. This Agreement, together with the Privacy Policy and any other legal notices published by us on the Services, shall constitute the entire agreement between you and us concerning the Services. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and our failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. YOU AND US AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.\n',
                ),
                TextSpan(
                  text: 'Waiver\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'Any failure by either party to exercise a right or enforce an obligation under this Agreement does not mean that they have given up that right or cannot enforce it later. Likewise, if one party overlooks a breach of the Agreement, it does not mean they are waiving their right to address any future breaches. Any delay in exercising a right or power does not nullify that right or power, and it doesn\'t prevent either party from exercising it in the future. Even if a party only partially exercises a right or power, they can still exercise it further in the future. In case of any conflict between this Agreement and any other applicable terms, the terms of this Agreement will take precedence.\n',
                ),
                TextSpan(
                  text: 'Amendments to this Agreement\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'We reserve the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material, we will provide at least 30 days’ notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use our service.\n',
                ),
                TextSpan(
                  text: 'Entire Agreement\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'The Agreement constitutes the entire agreement between you and ePolli regarding your use of the service and supersedes all prior and simultaneous written or oral agreements between you and us. You may be subject to additional terms and conditions that apply when you use or purchase other services from us, which we will provide to you at the time of such use or purchase.\n',
                ),
                TextSpan(
                  text: 'Updates to Our Terms\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'ePolli may change our Service and policies, and we may need to make changes to these Terms so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to these Terms and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Terms. If you do not want to agree to these or any updated Terms, you can delete your account at any time.\n',
                ),
                TextSpan(
                  text: 'Intellectual Property\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'Our platform, including all of its contents, features, and functionalities (such as information, software, text, displays, images, videos, and audio, as well as their design, selection, and arrangement), is the property of ePolli, its licensors, or other providers who hold rights to such materials. These elements are safeguarded by both Bangladesh and international laws governing copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights.\n\nCopying, modifying, reproducing, downloading, or distributing the material, either in whole or in part, is strictly prohibited without obtaining express prior written permission from ePolli, except as expressly provided in these Terms & Conditions. Any unauthorized use of the material is strictly prohibited and may result in legal consequences.\n',
                ),
                TextSpan(
                  text: 'Agreement to Arbitrate\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'This section is applicable to all disputes except those specifically related to claims for injunctive or equitable relief regarding the enforcement or validity of your or ePolli\'s intellectual property rights. The term "dispute" encompasses any disagreement, legal action, or other contentious matter that may arise between you and ePolli concerning the Services or this agreement. This includes disputes based on contract, warranty, tort, statute, regulation, ordinance, or any other legal or equitable grounds. The term "dispute" will be interpreted with the broadest possible scope allowed by law.\n\n',
                ),
                TextSpan(
                  text: 'Notice of Dispute\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'If a dispute arises, either you or ePolli must provide the other party with a Notice of Dispute, which is a written statement containing the party\'s name, address, and contact information, along with the facts leading to the dispute and the requested relief. You are required to send the Notice of Dispute via email to support@epolli.com.bd. On the other hand, ePolli will send any Notice of Dispute to you by mail if your address is available, or to your email address otherwise.\n\nBoth parties, you and ePolli, will attempt to resolve the dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. If the dispute remains unresolved after this period, either you or ePolli may initiate arbitration to seek resolution.\n\n',
                ),
                TextSpan(
                  text: 'Binding Arbitration\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'If both parties, you and ePolli, are unable to resolve a dispute through informal negotiation, the exclusive method for resolving the dispute will be binding arbitration, as outlined in this section. By agreeing to this, you waive the right to litigate or participate in any disputes in court before a judge or jury as a party or class member.\n\nThe arbitration process shall adhere to the commercial arbitration rules of the American Arbitration Association. However, either party retains the right to seek interim or preliminary injunctive relief from a court of competent jurisdiction to safeguard their rights or property while the arbitration is ongoing.\n\nAll costs, fees, and expenses, including legal and accounting fees, incurred by the prevailing party in the arbitration shall be borne by the party that did not prevail.\n\n',
                ),
                TextSpan(
                  text: 'Submissions and Privacy\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'If you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data, or proposals to us, including ideas for new or improved products, services, features, technologies, or promotions, you agree that such submissions will be treated as non-confidential and non-proprietary. Consequently, these submissions will become the exclusive property of our company, without any obligation to provide compensation or credit to you.\n\nNeither we nor our affiliates will have any obligations concerning these submissions or posts, and we may freely use the ideas contained therein for any purpose, in any medium, indefinitely. This includes, but is not limited to, developing, manufacturing, and marketing products and services utilizing the concepts derived from these submissions or posts.\n',
                ),
                TextSpan(
                  text: 'Promotions\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'Occasionally, ePolli may introduce contests, promotions, sweepstakes, or other activities (referred to as "Promotions") that may necessitate you to provide material or personal information about yourself. Please be aware that each Promotion may be governed by separate rules that could include specific eligibility criteria, such as age or geographical restrictions. It is your responsibility to review all the rules associated with each Promotion to ascertain your eligibility for participation. By entering any Promotion, you commit to adhering to and complying with all the applicable Promotions Rules.\n\n',
                ),
                TextSpan(
                  text:
                      'Furthermore, there may be additional terms and conditions relevant to the purchase of goods or services through the Services. These terms and conditions become an integral part of this Agreement by virtue of this reference. It is important to thoroughly understand and abide by these additional terms when making any purchases through the Services.\n\n',
                ),
                TextSpan(
                  text: 'Typographical Errors\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'In the unlikely event that a product and/or service is displayed on our platform with an incorrect price or erroneous information due to a typographical error, we reserve the right to decline or cancel any orders placed for such products and/or services that are listed with the inaccurate price or information. This applies regardless of whether the order has been confirmed and your credit card has already been charged.\n\nIn the event that your credit card has been charged for the purchase and we subsequently cancel your order, we will promptly issue a credit to your credit card account or the relevant payment account for the exact amount of the charge.\n\nWe strive to ensure accuracy and precision in all aspects of our platform, but in the case of any inadvertent errors, we will take appropriate measures to rectify the situation promptly and transparently.\n\n',
                ),
                TextSpan(
                  text: 'Miscellaneous\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'In the event that any provision or portion of these Terms & Conditions is deemed unenforceable by a court of competent jurisdiction, the remaining provisions shall continue to remain valid and in effect. Any waiver of any provision in these Terms & Conditions will be deemed effective only if it is in writing and signed by an authorized representative of ePolli. If you breach or anticipate breaching any aspect of these Terms & Conditions, we reserve the right to seek injunctive or equitable relief without the requirement of posting any bond or surety.\n\n',
                ),
                TextSpan(
                  text:
                      'ePolli operates and controls its Service from its offices in Bangladesh. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would contravene the law or regulations. Hence, those who access our Service from other locations do so at their own discretion and are solely responsible for complying with the applicable local laws.\n\n',
                ),
                TextSpan(
                  text:
                      'These Terms & Conditions, which incorporate our Privacy Policy, constitute the entire agreement between you and ePolli, superseding any prior understandings on the subject matter, and cannot be altered or amended by you. The section headings utilized in this Agreement are for convenience purposes only and do not hold legal significance.\n\n',
                ),
                TextSpan(
                  text: 'Disclaimer\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'We want to clarify that we are not accountable for any content, code, or inaccuracies present in the Service. We do not provide warranties or guarantees of any kind. Under no circumstances shall we be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether arising from a contract, negligence, or other tort, in connection with the use of the Service or its contents. We retain the right to make additions, deletions, or modifications to the Service\'s contents without prior notice.\n\n',
                ),
                TextSpan(
                  text:
                      'Our Service and its contents are provided on an "as is" and "as available" basis, with no warranty or representation, whether express or implied. As a distributor and not a publisher of third-party content, we exercise no editorial control over such content and make no warranty or representation regarding the accuracy, reliability, or currency of any information, content, service, or merchandise accessible through our Service. Specifically, we disclaim all warranties and representations related to any content transmitted on or connected to our Service or on linked sites, or in products associated with our Service, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement of third-party rights.\n\n',
                ),
                TextSpan(
                  text:
                      'We do not create warranties through oral advice or written information provided by us, our affiliates, employees, officers, directors, agents, or similar individuals. The price and availability information may change without notice. Additionally, we do not guarantee that our Service will be uninterrupted, free from corruption, timely, or error-free.\n\n',
                ),
                TextSpan(
                  text: 'Contact Us\n',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                TextSpan(
                  text:
                      'Don’t hesitate to contact us if you have any questions.\n\n• Via Email: support@epolli.com.bd\n• Via Phone Number: 01798101013, 09678221013\n• Via this Address: 6/5 Ali-Noor Real State, 2nd Floor, Mohammadpur, Dhaka, 1207, Bangladesh\n',
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
